### ISSUE TITLE
Github giving a deprecation warning when running this Action

### ISSUE THREAD

**Issue by OutpostRyan** [TryGhost/action-deploy-theme#77] opened 2022-12-05 19:54 UTC
Using this file:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.6.1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}

Github action appears to work, but get this message:

deployNode.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: TryGhost/action-deploy-theme@v1.6.1
--

**Comment by ErisDS** [comment] 2022-12-16 23:52
Closing as a duplicate of https://github.com/TryGhost/action-deploy-theme/issues/76

**Closed by ErisDS** 2022-12-16 23:52 UTC
